# Generated by Django 4.2.6 on 2023-10-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('failure', 'неудачно')], default='success', verbose_name='Статус попытки'),
        ),
    ]
