# Generated by Django 4.2.6 on 2023-10-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailinglogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания рассылки'),
        ),
    ]
