# Generated by Django 4.2.6 on 2023-10-11 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='owner',
        ),
    ]
