# Generated by Django 4.2.6 on 2023-10-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='message',
            name='theme',
            field=models.CharField(max_length=100, verbose_name='Тема сообщения'),
        ),
    ]
